version: '3.8'

services:
  postgres:
    container_name: mycampus-postgres
    image: postgres:16.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mycampus
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: mycampus-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
